// Code generated by generate_examples.go; DO NOT EDIT.
package xtemplate_test

import (
	"fmt"

	"github.com/Eun/xtemplate"
	"github.com/Eun/xtemplate/funcs"
)

func ExampleConv_ToBool() {
	s, _ := xtemplate.QuickExecute(
		`{{ conv.ToBool "true" }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: true
}

func ExampleConv_ToBools() {
	s, _ := xtemplate.QuickExecute(
		`{{ $sl := slice.New "true" "false" 1 0 "yes" "no" }}
{{ conv.ToBools $sl }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: [true false true false true false]
}

func ExampleConv_ToFloat32() {
	s, _ := xtemplate.QuickExecute(
		`{{ conv.ToFloat32 "3.14" }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: 3.14
}

func ExampleConv_ToFloat32s() {
	s, _ := xtemplate.QuickExecute(
		`{{ $sl := slice.New "3.14" 42 "1e10" }}
{{ conv.ToFloat32s $sl }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: [3.14 42 1e+10]
}

func ExampleConv_ToFloat64() {
	s, _ := xtemplate.QuickExecute(
		`{{ conv.ToFloat64 "3.14" }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: 3.14
}

func ExampleConv_ToFloat64s() {
	s, _ := xtemplate.QuickExecute(
		`{{ $sl := slice.New "3.14" 42 "1e10" }}
{{ conv.ToFloat64s $sl }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: [3.14 42 1e+10]
}

func ExampleConv_ToInt() {
	s, _ := xtemplate.QuickExecute(
		`{{ conv.ToInt "42" }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: 42
}

func ExampleConv_ToInt16() {
	s, _ := xtemplate.QuickExecute(
		`{{ conv.ToInt16 "42" }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: 42
}

func ExampleConv_ToInt16s() {
	s, _ := xtemplate.QuickExecute(
		`{{ $sl := slice.New "42" 7 "0x10" }}
{{ conv.ToInt16s $sl }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: [42 7 16]
}

func ExampleConv_ToInt32() {
	s, _ := xtemplate.QuickExecute(
		`{{ conv.ToInt32 "42" }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: 42
}

func ExampleConv_ToInt32s() {
	s, _ := xtemplate.QuickExecute(
		`{{ $sl := slice.New "42" 7 "0x10" }}
{{ conv.ToInt32s $sl }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: [42 7 16]
}

func ExampleConv_ToInt64() {
	s, _ := xtemplate.QuickExecute(
		`{{ conv.ToInt64 "42" }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: 42
}

func ExampleConv_ToInt8() {
	s, _ := xtemplate.QuickExecute(
		`{{ conv.ToInt8 "42" }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: 42
}

func ExampleConv_ToInt8s() {
	s, _ := xtemplate.QuickExecute(
		`{{ $sl := slice.New "42" 7 "0x10" }}
{{ conv.ToInt8s $sl }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: [42 7 16]
}

func ExampleConv_ToInts() {
	s, _ := xtemplate.QuickExecute(
		`{{ $sl := slice.New "42" 7 "0x10" }}
{{ conv.ToInts $sl }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: [42 7 16]
}

func ExampleConv_ToString() {
	s, _ := xtemplate.QuickExecute(
		`{{ conv.ToString 42 }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: 42
}

func ExampleConv_ToStrings() {
	s, _ := xtemplate.QuickExecute(
		`{{ $sl := slice.New 42 true 3.14 }}
{{ conv.ToStrings $sl }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: [42 true 3.14]
}

func ExampleConv_ToUint() {
	s, _ := xtemplate.QuickExecute(
		`{{ conv.ToUint "42" }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: 42
}

func ExampleConv_ToUint16() {
	s, _ := xtemplate.QuickExecute(
		`{{ conv.ToUint16 "42" }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: 42
}

func ExampleConv_ToUint16s() {
	s, _ := xtemplate.QuickExecute(
		`{{ $sl := slice.New "42" 7 "0x10" }}
{{ conv.ToUint16s $sl }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: [42 7 16]
}

func ExampleConv_ToUint32() {
	s, _ := xtemplate.QuickExecute(
		`{{ conv.ToUint32 "42" }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: 42
}

func ExampleConv_ToUint32s() {
	s, _ := xtemplate.QuickExecute(
		`{{ $sl := slice.New "42" 7 "0x10" }}
{{ conv.ToUint32s $sl }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: [42 7 16]
}

func ExampleConv_ToUint64() {
	s, _ := xtemplate.QuickExecute(
		`{{ conv.ToUint64 "42" }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: 42
}

func ExampleConv_ToUint8() {
	s, _ := xtemplate.QuickExecute(
		`{{ conv.ToUint8 "42" }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: 42
}

func ExampleConv_ToUint8s() {
	s, _ := xtemplate.QuickExecute(
		`{{ $sl := slice.New "42" 7 "0x10" }}
{{ conv.ToUint8s $sl }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: [42 7 16]
}

func ExampleConv_ToUints() {
	s, _ := xtemplate.QuickExecute(
		`{{ $sl := slice.New "42" 7 "0x10" }}
{{ conv.ToUints $sl }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: [42 7 16]
}

