// Code generated by generate_examples.go; DO NOT EDIT.
package xtemplate_test

import (
	"fmt"

	"github.com/Eun/xtemplate"
	"github.com/Eun/xtemplate/funcs"
)

func ExampleCmp_Or() {
	s, _ := xtemplate.QuickExecute(
		`{{ cmp.Or "" "Hello" "World" }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: Hello
}

func ExampleCmp_Or_second() {
	s, _ := xtemplate.QuickExecute(
		`{{ cmp.Or 0 1 2 }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: 1
}

func ExampleCmp_Or_third() {
	s, _ := xtemplate.QuickExecute(
		`{{ cmp.Or ( slice.NewStrings "" "Hello" "World" ) }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: Hello
}

