// Code generated by generate_examples.go; DO NOT EDIT.
package xtemplate_test

import (
	"fmt"

	"github.com/Eun/xtemplate"
	"github.com/Eun/xtemplate/funcs"
)

func ExampleDict_HasKey() {
	s, _ := xtemplate.QuickExecute(
		`{{ dict.HasKey (dict.New "name" "Frank" "age" 42) "name" }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: true
}

func ExampleDict_HasKey_second() {
	s, _ := xtemplate.QuickExecute(
		`{{ dict.HasKey (dict.New "name" "Frank" "age" 42) "email" }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: false
}

func ExampleDict_HasValue() {
	s, _ := xtemplate.QuickExecute(
		`{{ dict.HasValue (dict.New "name" "Frank" "age" 42) 42 }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: true
}

func ExampleDict_HasValue_second() {
	s, _ := xtemplate.QuickExecute(
		`{{ dict.HasValue (dict.New "name" "Frank" "age" 42) "Joe" }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: false
}

func ExampleDict_Keys() {
	s, _ := xtemplate.QuickExecute(
		`{{ $dict := dict.New "name" "Frank" "age" 42 }}
{{ $keys := conv.ToStrings ( dict.Keys $dict ) }}
{{ slice.Sort $keys }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: [age name]
}

func ExampleDict_New() {
	s, _ := xtemplate.QuickExecute(
		`{{ dict.New "name" "Frank" "age" 42 }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: map[age:42 name:Frank]
}

