// Code generated by generate_examples.go; DO NOT EDIT.
package xtemplate_test

import (
	"fmt"

	"github.com/Eun/xtemplate"
	"github.com/Eun/xtemplate/funcs"
)

func ExampleFilePath_Base() {
	s, _ := xtemplate.QuickExecute(
		`{{ filepath.Base "/foo/bar/baz.js" }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: baz.js
}

func ExampleFilePath_Clean() {
	s, _ := xtemplate.QuickExecute(
		`{{ filepath.Clean "/foo//bar/../baz" }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: /foo/baz
}

func ExampleFilePath_Dir() {
	s, _ := xtemplate.QuickExecute(
		`{{ filepath.Dir "/foo/bar/baz.js" }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: /foo/bar
}

func ExampleFilePath_Ext() {
	s, _ := xtemplate.QuickExecute(
		`{{ filepath.Ext "/foo/bar/baz.js" }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: .js
}

func ExampleFilePath_Join() {
	s, _ := xtemplate.QuickExecute(
		`{{ filepath.Join "foo" "bar" "baz" }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: foo/bar/baz
}

func ExampleFilePath_Rel() {
	s, _ := xtemplate.QuickExecute(
		`{{ filepath.Rel "/a" "/a/b/c" }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: b/c
}

