// Code generated by generate_examples.go; DO NOT EDIT.
package xtemplate_test

import (
	"fmt"

	"github.com/Eun/xtemplate"
	"github.com/Eun/xtemplate/funcs"
)

func ExampleJSON_Marshal() {
	s, _ := xtemplate.QuickExecute(
		`{{ $dict := dict.New "foo" "bar" }}
{{ $buf := json.Marshal $dict }}
{{ conv.ToString $buf }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: {"foo":"bar"}
}

