// Code generated by generate_examples.go; DO NOT EDIT.
package xtemplate_test

import (
	"fmt"

	"github.com/Eun/xtemplate"
	"github.com/Eun/xtemplate/funcs"
)

func ExamplePath_Base() {
	s, _ := xtemplate.QuickExecute(
		`{{ path.Base "/foo/bar/baz" }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: baz
}

func ExamplePath_Clean() {
	s, _ := xtemplate.QuickExecute(
		`{{ path.Clean "/foo//bar/../baz" }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: /foo/baz
}

func ExamplePath_Dir() {
	s, _ := xtemplate.QuickExecute(
		`{{ path.Dir "/foo/bar/baz" }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: /foo/bar
}

func ExamplePath_Ext() {
	s, _ := xtemplate.QuickExecute(
		`{{ path.Ext "/foo/bar/baz.js" }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: .js
}

func ExamplePath_Join() {
	s, _ := xtemplate.QuickExecute(
		`{{ path.Join "foo" "bar" "baz" }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: foo/bar/baz
}

