// Code generated by generate_examples.go; DO NOT EDIT.
package xtemplate_test

import (
	"fmt"

	"github.com/Eun/xtemplate"
	"github.com/Eun/xtemplate/funcs"
)

func ExampleTmpl_Exec() {
	s, _ := xtemplate.QuickExecute(
		`{{ define "T1" }}Hello {{ . }}{{ end }}
{{ $result := tmpl.Exec "T1" "World" }}
Message: {{ $result }}`,
		nil,
		funcs.All,
	)
	fmt.Println(s) // Output: Message: Hello World
}

