// Code generated by generate_funcs.go; DO NOT EDIT.

package funcs

// Methods
var (
	CmpOr = Func { "cmp", "Or" }
	ConvToBool = Func { "conv", "ToBool" }
	ConvToBools = Func { "conv", "ToBools" }
	ConvToFloat32 = Func { "conv", "ToFloat32" }
	ConvToFloat32s = Func { "conv", "ToFloat32s" }
	ConvToFloat64 = Func { "conv", "ToFloat64" }
	ConvToFloat64s = Func { "conv", "ToFloat64s" }
	ConvToInt = Func { "conv", "ToInt" }
	ConvToInt16 = Func { "conv", "ToInt16" }
	ConvToInt16s = Func { "conv", "ToInt16s" }
	ConvToInt32 = Func { "conv", "ToInt32" }
	ConvToInt32s = Func { "conv", "ToInt32s" }
	ConvToInt64 = Func { "conv", "ToInt64" }
	ConvToInt64s = Func { "conv", "ToInt64s" }
	ConvToInt8 = Func { "conv", "ToInt8" }
	ConvToInt8s = Func { "conv", "ToInt8s" }
	ConvToInts = Func { "conv", "ToInts" }
	ConvToString = Func { "conv", "ToString" }
	ConvToStrings = Func { "conv", "ToStrings" }
	ConvToUint = Func { "conv", "ToUint" }
	ConvToUint16 = Func { "conv", "ToUint16" }
	ConvToUint16s = Func { "conv", "ToUint16s" }
	ConvToUint32 = Func { "conv", "ToUint32" }
	ConvToUint32s = Func { "conv", "ToUint32s" }
	ConvToUint64 = Func { "conv", "ToUint64" }
	ConvToUint64s = Func { "conv", "ToUint64s" }
	ConvToUint8 = Func { "conv", "ToUint8" }
	ConvToUint8s = Func { "conv", "ToUint8s" }
	ConvToUints = Func { "conv", "ToUints" }
	DictHasKey = Func { "dict", "HasKey" }
	DictHasValue = Func { "dict", "HasValue" }
	DictKeys = Func { "dict", "Keys" }
	DictNew = Func { "dict", "New" }
	FilePathAbs = Func { "filepath", "Abs" }
	FilePathBase = Func { "filepath", "Base" }
	FilePathClean = Func { "filepath", "Clean" }
	FilePathDir = Func { "filepath", "Dir" }
	FilePathExt = Func { "filepath", "Ext" }
	FilePathJoin = Func { "filepath", "Join" }
	FilePathRel = Func { "filepath", "Rel" }
	JSONCompact = Func { "json", "Compact" }
	JSONHTMLEscape = Func { "json", "HTMLEscape" }
	JSONIndent = Func { "json", "Indent" }
	JSONMarshal = Func { "json", "Marshal" }
	JSONMarshalIndent = Func { "json", "MarshalIndent" }
	JSONUnmarshal = Func { "json", "Unmarshal" }
	JSONValid = Func { "json", "Valid" }
	OSChdir = Func { "os", "Chdir" }
	OSChmod = Func { "os", "Chmod" }
	OSChown = Func { "os", "Chown" }
	OSChtimes = Func { "os", "Chtimes" }
	OSClearenv = Func { "os", "Clearenv" }
	OSEnviron = Func { "os", "Environ" }
	OSExecutable = Func { "os", "Executable" }
	OSExit = Func { "os", "Exit" }
	OSExpand = Func { "os", "Expand" }
	OSExpandEnv = Func { "os", "ExpandEnv" }
	OSGetegid = Func { "os", "Getegid" }
	OSGetenv = Func { "os", "Getenv" }
	OSGeteuid = Func { "os", "Geteuid" }
	OSGetgid = Func { "os", "Getgid" }
	OSGetgroups = Func { "os", "Getgroups" }
	OSGetpagesize = Func { "os", "Getpagesize" }
	OSGetpid = Func { "os", "Getpid" }
	OSGetppid = Func { "os", "Getppid" }
	OSGetuid = Func { "os", "Getuid" }
	OSGetwd = Func { "os", "Getwd" }
	OSHostname = Func { "os", "Hostname" }
	OSIsExist = Func { "os", "IsExist" }
	OSIsNotExist = Func { "os", "IsNotExist" }
	OSIsPathSeparator = Func { "os", "IsPathSeparator" }
	OSIsPermission = Func { "os", "IsPermission" }
	OSIsTimeout = Func { "os", "IsTimeout" }
	OSLchown = Func { "os", "Lchown" }
	OSLink = Func { "os", "Link" }
	OSLookupEnv = Func { "os", "LookupEnv" }
	OSMkdir = Func { "os", "Mkdir" }
	OSMkdirAll = Func { "os", "MkdirAll" }
	OSMkdirTemp = Func { "os", "MkdirTemp" }
	OSNewSyscallError = Func { "os", "NewSyscallError" }
	OSPipe = Func { "os", "Pipe" }
	OSReadFile = Func { "os", "ReadFile" }
	OSReadlink = Func { "os", "Readlink" }
	OSRemove = Func { "os", "Remove" }
	OSRemoveAll = Func { "os", "RemoveAll" }
	OSRename = Func { "os", "Rename" }
	OSSameFile = Func { "os", "SameFile" }
	OSSetenv = Func { "os", "Setenv" }
	OSSymlink = Func { "os", "Symlink" }
	OSTempDir = Func { "os", "TempDir" }
	OSTruncate = Func { "os", "Truncate" }
	OSUnsetenv = Func { "os", "Unsetenv" }
	OSUserCacheDir = Func { "os", "UserCacheDir" }
	OSUserConfigDir = Func { "os", "UserConfigDir" }
	OSUserHomeDir = Func { "os", "UserHomeDir" }
	OSWriteFile = Func { "os", "WriteFile" }
	PathBase = Func { "path", "Base" }
	PathClean = Func { "path", "Clean" }
	PathDir = Func { "path", "Dir" }
	PathExt = Func { "path", "Ext" }
	PathJoin = Func { "path", "Join" }
	RegexpFindAllString = Func { "regexp", "FindAllString" }
	RegexpFindAllStringIndex = Func { "regexp", "FindAllStringIndex" }
	RegexpFindAllStringSubmatch = Func { "regexp", "FindAllStringSubmatch" }
	RegexpFindAllStringSubmatchIndex = Func { "regexp", "FindAllStringSubmatchIndex" }
	RegexpFindString = Func { "regexp", "FindString" }
	RegexpFindStringIndex = Func { "regexp", "FindStringIndex" }
	RegexpFindStringSubmatch = Func { "regexp", "FindStringSubmatch" }
	RegexpFindStringSubmatchIndex = Func { "regexp", "FindStringSubmatchIndex" }
	RegexpMatchString = Func { "regexp", "MatchString" }
	RegexpQuoteMeta = Func { "regexp", "QuoteMeta" }
	RegexpReplaceAllLiteralString = Func { "regexp", "ReplaceAllLiteralString" }
	RegexpReplaceAllString = Func { "regexp", "ReplaceAllString" }
	RegexpSplit = Func { "regexp", "Split" }
	SliceAppend = Func { "slice", "Append" }
	SliceCompact = Func { "slice", "Compact" }
	SliceContains = Func { "slice", "Contains" }
	SliceLen = Func { "slice", "Len" }
	SliceNew = Func { "slice", "New" }
	SliceNewBools = Func { "slice", "NewBools" }
	SliceNewFloat64s = Func { "slice", "NewFloat64s" }
	SliceNewInt64s = Func { "slice", "NewInt64s" }
	SliceNewInts = Func { "slice", "NewInts" }
	SliceNewStrings = Func { "slice", "NewStrings" }
	SlicePrepend = Func { "slice", "Prepend" }
	SliceReverse = Func { "slice", "Reverse" }
	SliceSort = Func { "slice", "Sort" }
	SliceUnique = Func { "slice", "Unique" }
	StringsCompare = Func { "strings", "Compare" }
	StringsContains = Func { "strings", "Contains" }
	StringsContainsAny = Func { "strings", "ContainsAny" }
	StringsContainsRune = Func { "strings", "ContainsRune" }
	StringsCount = Func { "strings", "Count" }
	StringsCut = Func { "strings", "Cut" }
	StringsCutPrefix = Func { "strings", "CutPrefix" }
	StringsCutSuffix = Func { "strings", "CutSuffix" }
	StringsEqual = Func { "strings", "Equal" }
	StringsEqualFold = Func { "strings", "EqualFold" }
	StringsFields = Func { "strings", "Fields" }
	StringsHasPrefix = Func { "strings", "HasPrefix" }
	StringsHasSuffix = Func { "strings", "HasSuffix" }
	StringsIndex = Func { "strings", "Index" }
	StringsIndexAny = Func { "strings", "IndexAny" }
	StringsIndexByte = Func { "strings", "IndexByte" }
	StringsIndexRune = Func { "strings", "IndexRune" }
	StringsJoin = Func { "strings", "Join" }
	StringsLastIndex = Func { "strings", "LastIndex" }
	StringsLastIndexAny = Func { "strings", "LastIndexAny" }
	StringsLastIndexByte = Func { "strings", "LastIndexByte" }
	StringsRepeat = Func { "strings", "Repeat" }
	StringsReplace = Func { "strings", "Replace" }
	StringsReplaceAll = Func { "strings", "ReplaceAll" }
	StringsSplit = Func { "strings", "Split" }
	StringsSplitAfter = Func { "strings", "SplitAfter" }
	StringsSplitAfterN = Func { "strings", "SplitAfterN" }
	StringsSplitN = Func { "strings", "SplitN" }
	StringsToLower = Func { "strings", "ToLower" }
	StringsToTitle = Func { "strings", "ToTitle" }
	StringsToUpper = Func { "strings", "ToUpper" }
	StringsToValidUTF8 = Func { "strings", "ToValidUTF8" }
	StringsTrim = Func { "strings", "Trim" }
	StringsTrimLeft = Func { "strings", "TrimLeft" }
	StringsTrimPrefix = Func { "strings", "TrimPrefix" }
	StringsTrimRight = Func { "strings", "TrimRight" }
	StringsTrimSpace = Func { "strings", "TrimSpace" }
	StringsTrimSuffix = Func { "strings", "TrimSuffix" }
	TmplExec = Func { "tmpl", "Exec" }
	URLJoinPath = Func { "url", "JoinPath" }
	URLPathEscape = Func { "url", "PathEscape" }
	URLPathUnescape = Func { "url", "PathUnescape" }
	URLQueryEscape = Func { "url", "QueryEscape" }
	URLQueryUnescape = Func { "url", "QueryUnescape" }
)
// Collections
var (
	Cmp = Funcs {
		CmpOr,
	}

	Conv = Funcs {
		ConvToBool,
		ConvToBools,
		ConvToFloat32,
		ConvToFloat32s,
		ConvToFloat64,
		ConvToFloat64s,
		ConvToInt,
		ConvToInt16,
		ConvToInt16s,
		ConvToInt32,
		ConvToInt32s,
		ConvToInt64,
		ConvToInt64s,
		ConvToInt8,
		ConvToInt8s,
		ConvToInts,
		ConvToString,
		ConvToStrings,
		ConvToUint,
		ConvToUint16,
		ConvToUint16s,
		ConvToUint32,
		ConvToUint32s,
		ConvToUint64,
		ConvToUint64s,
		ConvToUint8,
		ConvToUint8s,
		ConvToUints,
	}

	Dict = Funcs {
		DictHasKey,
		DictHasValue,
		DictKeys,
		DictNew,
	}

	FilePath = Funcs {
		FilePathAbs,
		FilePathBase,
		FilePathClean,
		FilePathDir,
		FilePathExt,
		FilePathJoin,
		FilePathRel,
	}

	JSON = Funcs {
		JSONCompact,
		JSONHTMLEscape,
		JSONIndent,
		JSONMarshal,
		JSONMarshalIndent,
		JSONUnmarshal,
		JSONValid,
	}

	OS = Funcs {
		OSChdir,
		OSChmod,
		OSChown,
		OSChtimes,
		OSClearenv,
		OSEnviron,
		OSExecutable,
		OSExit,
		OSExpand,
		OSExpandEnv,
		OSGetegid,
		OSGetenv,
		OSGeteuid,
		OSGetgid,
		OSGetgroups,
		OSGetpagesize,
		OSGetpid,
		OSGetppid,
		OSGetuid,
		OSGetwd,
		OSHostname,
		OSIsExist,
		OSIsNotExist,
		OSIsPathSeparator,
		OSIsPermission,
		OSIsTimeout,
		OSLchown,
		OSLink,
		OSLookupEnv,
		OSMkdir,
		OSMkdirAll,
		OSMkdirTemp,
		OSNewSyscallError,
		OSPipe,
		OSReadFile,
		OSReadlink,
		OSRemove,
		OSRemoveAll,
		OSRename,
		OSSameFile,
		OSSetenv,
		OSSymlink,
		OSTempDir,
		OSTruncate,
		OSUnsetenv,
		OSUserCacheDir,
		OSUserConfigDir,
		OSUserHomeDir,
		OSWriteFile,
	}

	Path = Funcs {
		PathBase,
		PathClean,
		PathDir,
		PathExt,
		PathJoin,
	}

	Regexp = Funcs {
		RegexpFindAllString,
		RegexpFindAllStringIndex,
		RegexpFindAllStringSubmatch,
		RegexpFindAllStringSubmatchIndex,
		RegexpFindString,
		RegexpFindStringIndex,
		RegexpFindStringSubmatch,
		RegexpFindStringSubmatchIndex,
		RegexpMatchString,
		RegexpQuoteMeta,
		RegexpReplaceAllLiteralString,
		RegexpReplaceAllString,
		RegexpSplit,
	}

	Slice = Funcs {
		SliceAppend,
		SliceCompact,
		SliceContains,
		SliceLen,
		SliceNew,
		SliceNewBools,
		SliceNewFloat64s,
		SliceNewInt64s,
		SliceNewInts,
		SliceNewStrings,
		SlicePrepend,
		SliceReverse,
		SliceSort,
		SliceUnique,
	}

	Strings = Funcs {
		StringsCompare,
		StringsContains,
		StringsContainsAny,
		StringsContainsRune,
		StringsCount,
		StringsCut,
		StringsCutPrefix,
		StringsCutSuffix,
		StringsEqual,
		StringsEqualFold,
		StringsFields,
		StringsHasPrefix,
		StringsHasSuffix,
		StringsIndex,
		StringsIndexAny,
		StringsIndexByte,
		StringsIndexRune,
		StringsJoin,
		StringsLastIndex,
		StringsLastIndexAny,
		StringsLastIndexByte,
		StringsRepeat,
		StringsReplace,
		StringsReplaceAll,
		StringsSplit,
		StringsSplitAfter,
		StringsSplitAfterN,
		StringsSplitN,
		StringsToLower,
		StringsToTitle,
		StringsToUpper,
		StringsToValidUTF8,
		StringsTrim,
		StringsTrimLeft,
		StringsTrimPrefix,
		StringsTrimRight,
		StringsTrimSpace,
		StringsTrimSuffix,
	}

	Tmpl = Funcs {
		TmplExec,
	}

	URL = Funcs {
		URLJoinPath,
		URLPathEscape,
		URLPathUnescape,
		URLQueryEscape,
		URLQueryUnescape,
	}

	All = Funcs {
		CmpOr,
		ConvToBool,
		ConvToBools,
		ConvToFloat32,
		ConvToFloat32s,
		ConvToFloat64,
		ConvToFloat64s,
		ConvToInt,
		ConvToInt16,
		ConvToInt16s,
		ConvToInt32,
		ConvToInt32s,
		ConvToInt64,
		ConvToInt64s,
		ConvToInt8,
		ConvToInt8s,
		ConvToInts,
		ConvToString,
		ConvToStrings,
		ConvToUint,
		ConvToUint16,
		ConvToUint16s,
		ConvToUint32,
		ConvToUint32s,
		ConvToUint64,
		ConvToUint64s,
		ConvToUint8,
		ConvToUint8s,
		ConvToUints,
		DictHasKey,
		DictHasValue,
		DictKeys,
		DictNew,
		FilePathAbs,
		FilePathBase,
		FilePathClean,
		FilePathDir,
		FilePathExt,
		FilePathJoin,
		FilePathRel,
		JSONCompact,
		JSONHTMLEscape,
		JSONIndent,
		JSONMarshal,
		JSONMarshalIndent,
		JSONUnmarshal,
		JSONValid,
		OSChdir,
		OSChmod,
		OSChown,
		OSChtimes,
		OSClearenv,
		OSEnviron,
		OSExecutable,
		OSExit,
		OSExpand,
		OSExpandEnv,
		OSGetegid,
		OSGetenv,
		OSGeteuid,
		OSGetgid,
		OSGetgroups,
		OSGetpagesize,
		OSGetpid,
		OSGetppid,
		OSGetuid,
		OSGetwd,
		OSHostname,
		OSIsExist,
		OSIsNotExist,
		OSIsPathSeparator,
		OSIsPermission,
		OSIsTimeout,
		OSLchown,
		OSLink,
		OSLookupEnv,
		OSMkdir,
		OSMkdirAll,
		OSMkdirTemp,
		OSNewSyscallError,
		OSPipe,
		OSReadFile,
		OSReadlink,
		OSRemove,
		OSRemoveAll,
		OSRename,
		OSSameFile,
		OSSetenv,
		OSSymlink,
		OSTempDir,
		OSTruncate,
		OSUnsetenv,
		OSUserCacheDir,
		OSUserConfigDir,
		OSUserHomeDir,
		OSWriteFile,
		PathBase,
		PathClean,
		PathDir,
		PathExt,
		PathJoin,
		RegexpFindAllString,
		RegexpFindAllStringIndex,
		RegexpFindAllStringSubmatch,
		RegexpFindAllStringSubmatchIndex,
		RegexpFindString,
		RegexpFindStringIndex,
		RegexpFindStringSubmatch,
		RegexpFindStringSubmatchIndex,
		RegexpMatchString,
		RegexpQuoteMeta,
		RegexpReplaceAllLiteralString,
		RegexpReplaceAllString,
		RegexpSplit,
		SliceAppend,
		SliceCompact,
		SliceContains,
		SliceLen,
		SliceNew,
		SliceNewBools,
		SliceNewFloat64s,
		SliceNewInt64s,
		SliceNewInts,
		SliceNewStrings,
		SlicePrepend,
		SliceReverse,
		SliceSort,
		SliceUnique,
		StringsCompare,
		StringsContains,
		StringsContainsAny,
		StringsContainsRune,
		StringsCount,
		StringsCut,
		StringsCutPrefix,
		StringsCutSuffix,
		StringsEqual,
		StringsEqualFold,
		StringsFields,
		StringsHasPrefix,
		StringsHasSuffix,
		StringsIndex,
		StringsIndexAny,
		StringsIndexByte,
		StringsIndexRune,
		StringsJoin,
		StringsLastIndex,
		StringsLastIndexAny,
		StringsLastIndexByte,
		StringsRepeat,
		StringsReplace,
		StringsReplaceAll,
		StringsSplit,
		StringsSplitAfter,
		StringsSplitAfterN,
		StringsSplitN,
		StringsToLower,
		StringsToTitle,
		StringsToUpper,
		StringsToValidUTF8,
		StringsTrim,
		StringsTrimLeft,
		StringsTrimPrefix,
		StringsTrimRight,
		StringsTrimSpace,
		StringsTrimSuffix,
		TmplExec,
		URLJoinPath,
		URLPathEscape,
		URLPathUnescape,
		URLQueryEscape,
		URLQueryUnescape,
	}
)
var NamespacesAndTheirFunctions = map[string]map[string]struct{}{
	"cmp": {
		"Or": {},
	},
	"conv": {
		"ToBool": {},
		"ToBools": {},
		"ToFloat32": {},
		"ToFloat32s": {},
		"ToFloat64": {},
		"ToFloat64s": {},
		"ToInt": {},
		"ToInt16": {},
		"ToInt16s": {},
		"ToInt32": {},
		"ToInt32s": {},
		"ToInt64": {},
		"ToInt64s": {},
		"ToInt8": {},
		"ToInt8s": {},
		"ToInts": {},
		"ToString": {},
		"ToStrings": {},
		"ToUint": {},
		"ToUint16": {},
		"ToUint16s": {},
		"ToUint32": {},
		"ToUint32s": {},
		"ToUint64": {},
		"ToUint64s": {},
		"ToUint8": {},
		"ToUint8s": {},
		"ToUints": {},
	},
	"dict": {
		"HasKey": {},
		"HasValue": {},
		"Keys": {},
		"New": {},
	},
	"filepath": {
		"Abs": {},
		"Base": {},
		"Clean": {},
		"Dir": {},
		"Ext": {},
		"Join": {},
		"Rel": {},
	},
	"json": {
		"Compact": {},
		"HTMLEscape": {},
		"Indent": {},
		"Marshal": {},
		"MarshalIndent": {},
		"Unmarshal": {},
		"Valid": {},
	},
	"os": {
		"Chdir": {},
		"Chmod": {},
		"Chown": {},
		"Chtimes": {},
		"Clearenv": {},
		"Environ": {},
		"Executable": {},
		"Exit": {},
		"Expand": {},
		"ExpandEnv": {},
		"Getegid": {},
		"Getenv": {},
		"Geteuid": {},
		"Getgid": {},
		"Getgroups": {},
		"Getpagesize": {},
		"Getpid": {},
		"Getppid": {},
		"Getuid": {},
		"Getwd": {},
		"Hostname": {},
		"IsExist": {},
		"IsNotExist": {},
		"IsPathSeparator": {},
		"IsPermission": {},
		"IsTimeout": {},
		"Lchown": {},
		"Link": {},
		"LookupEnv": {},
		"Mkdir": {},
		"MkdirAll": {},
		"MkdirTemp": {},
		"NewSyscallError": {},
		"Pipe": {},
		"ReadFile": {},
		"Readlink": {},
		"Remove": {},
		"RemoveAll": {},
		"Rename": {},
		"SameFile": {},
		"Setenv": {},
		"Symlink": {},
		"TempDir": {},
		"Truncate": {},
		"Unsetenv": {},
		"UserCacheDir": {},
		"UserConfigDir": {},
		"UserHomeDir": {},
		"WriteFile": {},
	},
	"path": {
		"Base": {},
		"Clean": {},
		"Dir": {},
		"Ext": {},
		"Join": {},
	},
	"regexp": {
		"FindAllString": {},
		"FindAllStringIndex": {},
		"FindAllStringSubmatch": {},
		"FindAllStringSubmatchIndex": {},
		"FindString": {},
		"FindStringIndex": {},
		"FindStringSubmatch": {},
		"FindStringSubmatchIndex": {},
		"MatchString": {},
		"QuoteMeta": {},
		"ReplaceAllLiteralString": {},
		"ReplaceAllString": {},
		"Split": {},
	},
	"slice": {
		"Append": {},
		"Compact": {},
		"Contains": {},
		"Len": {},
		"New": {},
		"NewBools": {},
		"NewFloat64s": {},
		"NewInt64s": {},
		"NewInts": {},
		"NewStrings": {},
		"Prepend": {},
		"Reverse": {},
		"Sort": {},
		"Unique": {},
	},
	"strings": {
		"Compare": {},
		"Contains": {},
		"ContainsAny": {},
		"ContainsRune": {},
		"Count": {},
		"Cut": {},
		"CutPrefix": {},
		"CutSuffix": {},
		"Equal": {},
		"EqualFold": {},
		"Fields": {},
		"HasPrefix": {},
		"HasSuffix": {},
		"Index": {},
		"IndexAny": {},
		"IndexByte": {},
		"IndexRune": {},
		"Join": {},
		"LastIndex": {},
		"LastIndexAny": {},
		"LastIndexByte": {},
		"Repeat": {},
		"Replace": {},
		"ReplaceAll": {},
		"Split": {},
		"SplitAfter": {},
		"SplitAfterN": {},
		"SplitN": {},
		"ToLower": {},
		"ToTitle": {},
		"ToUpper": {},
		"ToValidUTF8": {},
		"Trim": {},
		"TrimLeft": {},
		"TrimPrefix": {},
		"TrimRight": {},
		"TrimSpace": {},
		"TrimSuffix": {},
	},
	"tmpl": {
		"Exec": {},
	},
	"url": {
		"JoinPath": {},
		"PathEscape": {},
		"PathUnescape": {},
		"QueryEscape": {},
		"QueryUnescape": {},
	},
}
